### ISSUE TITLE
v1.6.0 PDF genaration not working

### ISSUE THREAD

**Issue by leandro-effinger** [mhzawadi/invoiceplane#31]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

I just tested the version `1.6.0`. Even with debug enabled, I can not see any root cause for the problem, but once I have seen anything in the log that pointed to a missing PHP-Extension/library.

![image](https://github.com/mhzawadi/invoiceplane/assets/120006552/e471a75d-e198-45b1-8563-9641a469ef64)

Would be awesome if you could test it against this error.

Thanks for your great work! :)

**Comment by leandro-effinger** [comment]
Just wanted to add, that all PDFs are generated under the section `/reports/*`. But generating Quotes or Invoices does not work.

**Comment by mhzawadi** [comment]
Hi @leandro-effinger 

Thanks for your support, I have tested the 1.6.0 tag and PDFs generate just fine.

Could you tell me more about your setup?

- whats your compose file (minus and passwords)
- what OS and browser are you using
- are downloading the PDF or emailing

**Comment by the-hotmann** [comment]
I just tested the very same setup.

I tested a blank new installation from scratch - can confirm it does not work, when calling the URL `/guest/view/generate_invoice_pdf/[###random_string###]`.

Here is the `docker-compose`:

```
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:1.6.0
    volumes:
      - '/var/docker/config/invoiceplane/uploads/:/var/www/html/uploads/:rw'
      - '/var/docker/config/invoiceplane/config/ipconfig.php:/var/www/html/ipconfig.php:rw'
    environment:
      TZ: 'Europe/Berlin'
      MYSQL_HOST: 'DATABSE_HOST'
      MYSQL_USER: 'DATABASE_USER'
      MYSQL_PASSWORD: 'DATABASE_PASSWORD'
      MYSQL_DB: 'DATABASE_DB'
      IP_URL: 'https://sub.domain.tld'
      DISABLE_SETUP: true
    depends_on:
      - DATABSE_HOST
    restart: unless-stopped
```

Please be aware that ALL strings starting with `DATABASE_` have been replaced to avoid any personal information leaks. Additionally, apart from following the recommended Docker Compose setup, I ensured that the uploads folder remains persistent. Before the installation, all permissions and ownerships were set correctly.

The issue occurs when generating a **Quote** and then attempting to generate the PDF by accessing the link manually. PDF generation works correctly in all other instances.

Please also note that none of the MYSQL Database ENV Variables appear to be taking effect. When I have set the Config file, and the ENV Vars, then the config file always will be taken. The ENV Vars are not overwriting it.
