### ISSUE TITLE
V. latest / 1.6.0

### ISSUE THREAD

**Issue by leandro-effinger** [mhzawadi/invoiceplane#34]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

I was trying to initialize  the invoiceplane docker as a compose. After the language selection I get the following error. Can you help me out with that?

I tryed it with the latest and the v1.6.0

![image](https://github.com/mhzawadi/invoiceplane/assets/120006552/54b8e904-3cb1-440a-88be-50836c98674d)

For better understanding is hear a part of my compose file too:

```
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:latest
    volumes:
      - /var/docker/config/invoiceplane/app:/var/www/html/uploads
    environment:
      - TZ=Europe/Berlin
      - MYSQL_HOST=mariadb_10_4
      - MYSQL_USER=InvoicePlane
      - MYSQL_PASSWORD=changeme
      - MYSQL_DB=InvoicePlane
      - IP_URL=http://invoiceplane.domain.de
      - DISABLE_SETUP=false
    restart: unless-stopped
    depends_on:
      - postgres

  mariadb_10_4:
    container_name: ip_mariadb
    # MySQL 5.7
    image: mariadb:10.4.10
    volumes:
      - /var/docker/config/invoiceplane/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=invoiceplane
      - MYSQL_USER=invoiceplane
      - MYSQL_PASSWORD=changeme
    restart: unless-stopped
```

---

I was the guy who published the bug with the broken PDF generator.
https://github.com/mhzawadi/invoiceplane/issues/31

I was trying to complete re initialize the the docker compose on a clean system and got this new bug.

thanks in advance.
