### ISSUE TITLE
can't run commands

### ISSUE THREAD

**Issue by cachho** [mhzawadi/invoiceplane#56]
**Describe the bug**
I get the following error (which is a invoiceplane issue) `Unable to load the requested language file: language/American-English/ip_lang.php`
To combat this I have to copy the `english` folder as `American-English`.
I try to do this by adding a command to the docker-compose.
However, once I do that, the container does not start.

These are the logs

```
ln: /var/log/php81/error.log: File exists

ln: /var/log/nginx/access.log: File exists

ln: /var/log/nginx/error.log: File exists

sed: can't move '/var/www/html/ipconfig.phpkGPmOO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpGBeHdO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpmobPeO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpOKElfO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpMpaDhO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpCnaIiO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpKoLOjO' to '/var/www/html/ipconfig.php': Resource busy

sed: can't move '/var/www/html/ipconfig.phpfKOekO' to '/var/www/html/ipconfig.php': Resource busy

hello world
```

It also doesn't seem to like me making the ipconfig.php file persistent, but if I don't, I have to go through the setup every time I start the app. But looking at it it might be because my env vars start with `MYSQL_` and this is mariadb.

**To Reproduce**
See docker-compose file at the bottom.

I tried to use echo to make sure it's not the actual command.
in practice I would run `cp -r application/language/english application/language/American-English`

It works without the command.

**Expected behavior**
Being able to run a command.

**Screenshots**

![Image](https://github.com/user-attachments/assets/3fef8ae4-15af-4cc3-abda-088d675ba289)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

My docker-compose file

```yaml
version: '3.5'

# docker stack deploy --compose-file stack-invoiceplane.yml invoiceplane

networks:
  nginx-proxy-manager-network:
    name: nginx-proxy-manager-network
    external: true
    driver: bridge
  internal-net:
    name: internal-net
    driver: bridge

volumes:
  invoiceplane_data:
  invoiceplane_mariadb_10_4:

services:
  invoiceplane:
    container_name: invoiceplane
    image: mhzawadi/invoiceplane:latest
    restart: always
    volumes:
      - invoiceplane_data:/var/www/html/uploads
      - /export/nas/invoiceplane/ipconfig.php:/var/www/html/ipconfig.php
      - /export/nas/invoiceplane/InvoicePlane.php:/var/www/html/application/views/invoice_templates/pdf/InvoicePlane.php
    command: echo "hello world"

    ports:
      - 80
    networks:
      - nginx-proxy-manager-network
      - internal-net
    env_file: stack.env
    depends_on:
      - invoiceplane_mariadb

  invoiceplane_mariadb:
    # MySQL 5.7
    container_name: invoiceplane_mariadb
    image: mariadb:10.4.10
    restart: always
    volumes:
      - invoiceplane_mariadb_10_4:/var/lib/mysql
    env_file: stack.env
    networks:
      - internal-net
    ports:
      - 3306
```
